name: Redis-Exclusive

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: redis-exclusive-php
    volumes:
      - ../:/var/www/redis-exclusive
    ports:
      - "9000:9000"
    depends_on:
      - redis
    command: php-fpm

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis-exclusive-redis
    ports:
      - "6379:6379"
